### PR TITLE
Avoid copy when the plugin returns

### PR DESCRIPTION
**Pull request by arnaudgolfouse**
This should avoid copying the data until another function is called.

### CODE REVIEW

**Comment by arnaudgolfouse** [comment]
Some notes:

## There's a lifetime !

Functions now return `ReturnedData<'a>`, preventing any other function being called while this structure is alive.

Technically the data returned by a function should no longer be accessible from inside the plugin after the return (_if_ the plugin respect the spirit of the protocol), so maybe we could get away with the lifetime if absolutely needed (using a `Rc<RefCell>/Arc<Mutex>` for example).

## Why not return `ptr`/`len` directly ?

The call to `wasm_minimal_protocol_send_result_to_host` seems redundant, does it not ? Well, I tried having plugin functions be something like
```rust
pub extern "C" fn hello() -> (*const u8, usize, i32) {
    let message = String::from("Hello world!");
    let (ptr, len, code) = (message.as_ptr(), message.len(), 0);
    std::mem::forget(message);
    (ptr, len, code)
}
```

But it does not seems quite ready yet... It works on `wasm32-unknown-unknown` by setting the env variable `RUSTFLAGS="-C target-feature=+multivalue"`, which is already not ideal ; but then this breaks when using `wasm32-wasi`. See this (opened) issue: <https://github.com/rust-lang/rust/issues/73755>

**Comment by astrale-sharp** [comment]
This looks great, thanks a ton, it doesn't seem to be missing anything either, are you okay with me merging it?

<3

**Comment by arnaudgolfouse** [comment]
Oh wait, rereading this I see I slightly messed up the documentation

**Comment by arnaudgolfouse** [comment]
Ok, looks good to me !

**Pull request merged**
